development:
  host: localhost
  database: group_buy_development

test:
  host: localhost
  database: group_buy_test

# set these environment variables on your prod server
production:
  uri: <%= ENV["MONGODB"] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
